# Usando a imagem base do Nginx para servir arquivos estáticos
FROM nginx:latest

# Copiando todos os arquivos do frontend para o diretório padrão do Nginx
COPY . /usr/share/nginx/html

# Expondo a porta 80 para acesso externo
EXPOSE 80
